# Python for Scientists
## Day 1 Notebook
This notebook was developed for the NASA Goddard Space Flight Center and CRESST II's post-baccalaureate program by [Joe P. Renaud](https://www.josephrenaud.com) in Spring, 2024.

**Prerequisites for running this notebook**
- Install Python 3.9+ (e.g., by using [Anaconda](https://www.anaconda.com/download))
- (Optional but recommended) Create a new virtual environment or conda environment.
    - For conda: `conda create -n PyScience python="3.11"; conda activate PyScience`
- Open a terminal and install packages using pip (or `conda install`):
    - `pip install numpy scipy matplotlib jupyter`

# Overview of Jupyter Notebooks

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Define variables and print them
x = 20
print(f"x = {x}")

# Make and display plots
x = np.linspace(0., 4. * np.pi, 50)
y = np.sin(x)
fig, ax = plt.subplots()
ax.plot(x, y, c='r', label='My Data')
ax.legend(loc='best')
plt.show()

In [ ]:
# Variables are saved by order the notebook's cell is executed, _not_ in order of appearance.
print(x)

In [ ]:
# The x variable has changed, go back to the previous cell and try printing it now.
x = "red"

In [ ]:
# Other fun things you can do in a notebook
ls

# Python "Basics"

## Variables and Data Types
Common Python and Numpy variables and data types.

In [ ]:
# We are skipping some types but can get into them if there is interest:
# - Strings, tuples, classes, sets, iterables (generally)

In [ ]:
# Floating Point Numbers, an imperfect necessity
x = 1.0
print(type(x))
y = 1
print(type(y))

# All ways to define floats
x = 1.0e-2
x = 0.2E-1

print("\nBeware of the float!")
print("6.0/2.0 =", 6.0/2.0)
print("0.6/0.2 =", 0.6/0.2)
print("6.0/2.0 equals 0.6/0.2?", 6.0/2.0 == 0.6/0.2)
print("0.6//0.2 =", 0.6//0.2)

In [ ]:
# Lists
print("\nLists")
my_list = [1,2,3,4]
print("my list:", my_list)
print("It has", len(my_list), "members.")
my_list.append(10)
print("I can add 10 to it:", my_list)
for item in my_list:
    print("This item is", item)

for i, item in enumerate(my_list):
    print("Item", i, "is", item)

# "Slicing" a list
print("Item 0:", my_list[0])
print("Items 2 to end:", my_list[2:])
print("Items 2 to 2nd from end:", my_list[2:-1])
print("Skip Every Other Item:", my_list[0::2])
print("Skip Every Other Item (Evens):", my_list[1::2])

# Loop over slices of a list
for i, item in enumerate(my_list[0::2]):
    print("Item", i, "is", item)

print("My original list", my_list[:], "Or I can just do:", my_list)
# Lists can be changed: They are "mutable"
my_list[0] = 1000
print(my_list)
my_list[0:2] = [20, 25]
print(my_list)
# Notice that the slice is EXCLUSIVE (the value in spot "2" did not change)

# List members do not need to be of the same type (aka: all integers); they are "inhomogeneous"
t = "Blue"
my_new_list = [1, 2, 3, 2/3, "Hello There", t]
print("\n", my_new_list)

In [ ]:
# Numpy Arrays work very similar to lists for 1-D data (but are much faster and more memory efficient)
print("\nNumpy Arrays")
my_array = np.asarray([1,2,3,4])
print("my array:", my_array)
print("It has", len(my_array), "members.")
my_array = np.append(my_array, 10)  # There is a catch with the numpy append, see if you can figure it out or ask me about it!
print("I can add 10 to it:", my_array)
for item in my_array:
    print("This item is", item)

for i, item in enumerate(my_array):
    print("Item", i, "is", item)

print("Item 0:", my_array[0])
print("Items 2 to end:", my_array[2:])
print("Items 2 to 2nd from end:", my_array[2:-1])
print("Skip Every Other Item:", my_array[0::2])
print("Skip Every Other Item (Evens):", my_array[1::2])
print("My original list", my_list[:], "Or I can just do:", my_array)
# Numpy arrays are also mutable
my_array[0] = 1000
print(my_array)
my_array[0:2] = [20, 25]
print(my_array)

### Differences between Python lists and numpy arrays

In [ ]:
# Most* Numpy arrays are homogenous; lists are inhomogeneous. 
my_list = [0., 2, 'blue']
print(my_list)
my_array = np.asarray([0., 2, 'blue'])
print(my_array)
# This works!

my_list = [0, 1, 2]
my_list[1] = 'Blue'
print(my_list)
my_array = np.asarray([0, 1, 2])
my_array[1] = 'Blue'
# Error. Once a numpy array has been built its type is set and can not be changed. 

In [ ]:
# 2+ Dimensional data is easier (and faster) to work with using numpy arrays
my_2D_list = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
]
print('Row 2, Column 3 item: ', my_2D_list[1][2])

# Notice the difference in how we access the item
my_2D_array = np.asarray(my_2D_list)
print('Row 2, Column 3 item: ', my_2D_array[1, 2])

# Quickly learn details about an array
print('Array type: ', my_2D_array.dtype)
print('Array size (total number of members): ', my_2D_array.size)
print('Array shape (size in each dimension): ', my_2D_array.shape)

In [55]:
# Lots of different kinds of math can be performed on a numpy arrays directly.
print('Original Array:\n', my_2D_array, '\n')
print('Original List:\n', my_2D_list, '\n')

# Multiply array by 2
print('Doubled Array:\n', my_2D_array * 2, '\n')  # <-- Success!
print('Doubled List:\n', my_2D_list * 2, '\n')   # <-- No Error, but probably not what you were looking for...

# Take the square of the 2D array.
print('Squared Array:\n', my_2D_array**2, '\n')  # <-- Success!
print('Squared List:\n', my_2D_list**2, '\n')   # <-- Error


Original Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Original List:
 [[0, 1, 2], [3, 4, 5], [6, 7, 8]] 

Doubled Array:
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]] 

Doubled List:
 [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 1, 2], [3, 4, 5], [6, 7, 8]] 

Squared Array:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]] 



TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [59]:
# Numpy allows for "masking" data which is just a fancy way to slice an array.
# Create a boolean (True/False) mask array for our 2D array

# Python's modulus 2 function will produce zeros where ever the array can be evenly divided by 2 (evens)
mod_2 = my_2D_array % 2
# We will create a mask where ever there are zeros using a "==" comparison
only_evens_mask = mod_2 == 0

# Can apply this to our original array
print(my_2D_array, '\n\n', my_2D_array[only_evens_mask], '\n')

# The mask is a regular numpy array so has all the same features
print(only_evens_mask.size, only_evens_mask.shape, only_evens_mask.dtype)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [0 2 4 6 8] 

9 (3, 3) bool


## Functions

In [ ]:
# How do we make functions?
def my_func(x):
    if x <= 5:
        return x
    else:
        return -x

out = my_func(10)
print(out)

In [ ]:
# Why do we make functions?
#  - Reduce duplication of code: making debugging easier, potentially improving performance

x = np.linspace(0., 2.0 * np.pi, 50)
y = np.sin(x)

def make_plot(*data):
    
    x_array = data[0]
    y_array = data[1]

    fig, ax = plt.subplots()
    ax.plot(x_array, y_array, c='r')

    ax.set(title='My Plot', xlabel="$\\eta$ [Deg.]", ylabel='$\\mu^2$ [m s$^{-20}$]', yscale='linear', xscale='linear')

    return fig, ax

# Now we have one function that we can use to make a bunch of different plots without having to repeat
make_plot(x, y)
y_2 = np.cos(x)
make_plot(x, y_2)
y_3 = np.tan(x)
make_plot(x, y_3)

# And it is easy to make changes when one plot should have, for example, a different title than another.
fig_1, ax_1 = make_plot(x, y_2)
ax_1.set(title='My Other Plot')
plt.show()

In [ ]:
# Another use for functions is to perform complex calculations on arrays of data, called "vectorizing"
array = np.linspace(0, 10, 4, dtype=np.float64)

my_func_vectorized = np.vectorize(my_func)
# Pause point: What _is_ the `my_func_vectorized` variable right now?
# Answer: it is a numpy class function (a python class) that now takes an array rather than a float.
print(type(my_func_vectorized))
array_2 = my_func_vectorized(array)
print('Function Applied to an Array: ', array_2)

# Try to uncomment the below and see what happens if we did not use the np.vectorize function
# array_3 = my_func(array)

# Now if we ever want to change the behavior of our function we can just change the definition of my_func rather
# than finding all of the instances where the functionality was implemented manually.

# A lot of common functions have probably already been made by others and included in various packages. 
# Many of these already work with arrays without you having to do anything. 
print('Sin: ', np.sin(array))
print('Cos: ', np.cos(array))
print('Exp: ', np.exp(array))

from scipy.special import gamma
print('Gamma: ', gamma(array))

# Python Gotchas

## Variable Scope
Local vs. global variable scope.

In [ ]:
# Before you run this cell, what do you think will be printed?

x = [0, 3, 7]

def my_func(x):

    x = "blue"
    return x

my_func(x)
print(x)

# Uncomment the code below each "pause point" as you work through this cell
# Pause Point 1
# x = my_func(x)
# print(x)


# Pause Point 2
# x = [0, 3, 7]
# def my_func(y):
#     global x
#     x = "blue"
#     return x

# my_func(x)
# print(x)

# Pause Point 3
x = [0, 3, 7]

def my_func(x):

    x[1] = "blue"
    return x

my_func(x)
print(x)

In [ ]:
# How about now?

x = [0, 3, 7]

def my_func(x):

    x = "blue"
    return x

x = my_func(x)
print(x)